---
title: "LSA Errors & Warnings"
author: "Genelle Denzin"
date: "March 21, 2019"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

library(readxl)
library(tidyverse)
library(gt)
library(janitor)
library(plotly)
```

## Data Quality Flags Summary

Both years together, all CoC flags

```{r categories_plot}

coc_check <- function(coc, year) {
  coc_name <- read_xlsx(
    paste0("data/errors_warnings_", year, "_", coc, ".xlsx"),
    sheet = 2,
    range = "A1",
    col_names = "CoC"
  ) %>%
    pull(CoC)
  
  if_else(
    (coc == "bos" & coc_name == "OH-507 Ohio Balance of State CoC") |
      (coc == "mah" & coc_name == "OH-504 Youngstown/Mahoning County CoC"),
  "Correct CoC",
  "File named incorrectly"
  )
}

coc_check("bos", 2018)
coc_check("bos", 2019)
coc_check("mah", 2018)
coc_check("mah", 2019)

flags_2018_bos <- read_xlsx(
  "data/errors_warnings_2018_bos.xlsx",
  sheet = 4,
  skip = 4,
  col_types = "text"
)

flags_2019_bos <- read_xlsx(
  "data/errors_warnings_2019_bos.xlsx",
  sheet = 4,
  skip = 4,
  col_types = "text"
)

flags_2018_mah <- read_xlsx(
  "data/errors_warnings_2018_mah.xlsx",
  sheet = 3,
  skip = 4,
  col_types = "text"
)

flags_2019_mah <- read_xlsx(
  "data/errors_warnings_2019_mah.xlsx",
  sheet = 4,
  skip = 4,
  col_types = "text"
)

flags_bos <-
  rbind(flags_2018_bos,
        flags_2019_bos) %>% 
  clean_names() %>% 
  unique() %>%
  filter(!is.na(id_number))

flags_mah <-
  rbind(flags_2018_mah,
        flags_2019_mah) %>% 
  clean_names() %>% 
  unique() %>%
  filter(!is.na(id_number))

flags_all <-
  rbind(flags_mah,
        flags_bos) %>% 
  clean_names() %>% 
  unique() %>%
  filter(!is.na(id_number)) %>%
  mutate(coc = substr(internal, 1, 6))

flag_categories <- flags_all %>%
  group_by(type, category, coc) %>%
  summarise(NumberErrors = n()) %>%
  ungroup() %>% 
  arrange(desc(NumberErrors)) 

bos_categories <- plot_ly(
  flag_categories %>%
    filter(coc == "OH-507") %>%
    arrange(desc(NumberErrors)) %>%
    head(8L),
  x = ~ reorder(category, desc(NumberErrors)),
  y = ~ NumberErrors,
  type = 'bar',
  color = ~ category
) %>%
  layout(
    title = "LSA Categories BoS",
    showlegend = FALSE,
    xaxis =  list(
      title = ""
    )
  )

mah_categories <- plot_ly(
  flag_categories %>%
    filter(coc == "OH-504") %>%
    arrange(desc(NumberErrors)) %>%
    head(8L),
  x = ~ reorder(category, desc(NumberErrors)),
  y = ~ NumberErrors,
  type = 'bar',
  color = ~ category
) %>%
  layout(
    title = "LSA Categories Mahoning",
    showlegend = FALSE,
    xaxis =  list(
      title = ""
    )
  )

bos_categories

mah_categories

```


## Errors vs Warnings

```{r errorswarnings}

flag_type <- flags_all %>%
  group_by(type) %>%
  summarise(Flags = n()) %>%
  ungroup() %>% 
  arrange(desc(Flags)) 

plot_ly(
  flag_categories %>%
    arrange(desc(NumberErrors)),
  x = ~ reorder(type, desc(NumberErrors)),
  y = ~ NumberErrors,
  type = 'bar',
  name = ~ category,
  color = ~ category,
  colors = 'Blues'
) %>%
  layout(
    title = 'Errors and Warnings',
    showlegend = FALSE,
    xaxis = list(title = ''),
    yaxis = list(title = 'Count'),
    barmode = 'stack'
  )

```


## Categories Detail

```{r categories_detail}
gt(flag_categories)

```

## Flag Descriptions

```{r descriptions}

flag_descriptions <- flags_all %>%
  group_by(id_number, type, category, description_7) %>%
  summarise(NumberErrors = n()) %>%
  ungroup()

toptenflagtypes <- flag_descriptions %>% arrange(desc(NumberErrors)) %>% head(10L)

gt(toptenflagtypes)

```

## Utilization

```{r}
utilization <- flags_bos %>%
  filter(category == "Utilization") %>%
  group_by(description_7) %>%
  summarise(warnings = n())

utilization_project_ids <- flags_bos %>%
  filter(category == "Utilization" & description_13 == "HMIS Project ID") %>%
  group_by(description_7, value_14, value_18) %>%
  summarise(warnings = n())

```

# Errors

```{r}

errors_bos <- flags_bos %>%
  filter(type == "Error") %>%
  group_by(category) %>%
  summarise(NumberErrors = n()) %>%
  ungroup() %>% 
  arrange(desc(NumberErrors)) 

each_error_bos <- flags_bos %>%
  filter(type == "Error")

bos_errors <- plot_ly(
  errors_bos %>%
    arrange(desc(NumberErrors)) %>%
    head(8L),
  x = ~ reorder(category, desc(NumberErrors)),
  y = ~ NumberErrors,
  type = 'bar',
  color = ~ category
) %>%
  layout(
    title = "BoS Errors",
    showlegend = FALSE,
    xaxis =  list(
      title = ""
    )
  )

bos_errors


errors_mah <- flags_mah %>%
  filter(type == "Error") %>%
  group_by(category) %>%
  summarise(NumberErrors = n()) %>%
  ungroup() %>% 
  arrange(desc(NumberErrors)) 

each_error_mah <- flags_mah %>%
  filter(type == "Error")

mah_errors <- plot_ly(
  errors_mah %>%
    arrange(desc(NumberErrors)) %>%
    head(8L),
  x = ~ reorder(category, desc(NumberErrors)),
  y = ~ NumberErrors,
  type = 'bar',
  color = ~ category
) %>%
  layout(
    title = "Mahoning Errors",
    showlegend = FALSE,
    xaxis =  list(
      title = ""
    )
  )

mah_errors

```

